version: "3"
services:

  worker:
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - back-tier

  result:
    build: ./result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - result-tier

  poll:
    build: ./poll
    ports:
      - 5000:80
    depends_on:
      - redis
      - db
    networks:
      - poll-tier

  redis:
    image: redis
    expose: 
      - 6379
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  db-data:
    driver: local


networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge
